In [1]:
import cv2

In [2]:
#How do you understand an image?
#A Multidimensional Array - Has Rows and Columns - Each value is a pixel value
#3*3 Array = 9 pixels; 8 bits: 0-255; 0 - Black, 255 - Gray


In [3]:
import numpy

In [5]:
img = numpy.zeros((3,3),dtype = numpy.uint8)

In [8]:
print(img)
print(img.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
(3, 3)


In [9]:
#Converting a Gray-scale Image to Color Image
img1 = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)  #BGR color channel

In [12]:
print(img1)
print(img1.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
(3, 3, 3)


In [29]:
image = cv2.imread('C:/Users/lenovo/Downloads/Paint.JPG')

In [30]:
cv2.imwrite('C:/Users/lenovo/Downloads/Paint.PNG',image)

True

In [32]:
print(image)
print(image.shape)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
(240, 240, 3)


In [33]:
print(image.shape)

(240, 240, 3)


In [28]:
import os
randomByteArray = bytearray(os.urandom(120000))
flatnumpyarray = numpy.array(randomByteArray)

In [34]:
bgrImage = flatnumpyarray.reshape(100,400,3)


In [36]:
cv2.imwrite('randomBGR.png',bgrImage)

True