# 1) Loading the dataset

In [3]:
import pandas as pd
df = pd.read_csv('D:/Users/Lucky/(MDI3002)Foundations of Data Science(FALL-2021)/LAB/IMDB Dataset.csv')

In [4]:
df.shape
df.head(10)

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive
6  I sure would like to see a resurrection of a u...  positive
7  This show was an amazing, fresh & innovative i...  negative
8  Encouraged by the positive comments about this...  negative
9  If you like original gut wrenching laughter yo...  positive

In [5]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [6]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
countV = CountVectorizer() #initialise CountVectorizer
docs = np.array(['The Sun is Shining','The weather is pleasant',
                 'The Sun is shining,
                 the weather is sweet and one and one and one'])

In [7]:
bag = countV.fit_transform(docs)


In [8]:
print(countV.vocabulary_) 
#creates a dictionary with unique words in the docs and gives an index for each unique word


{'the': 7, 'sun': 5, 'is': 1, 'shining': 4, 'weather': 8, 'pleasant': 3, 'sweet': 6, 'and': 0, 'one': 2}


In [9]:
print(bag.toarray())

[[0 1 0 0 1 1 0 1 0]
 [0 1 0 1 0 0 0 1 1]
 [3 2 3 0 1 1 1 2 1]]


# 2) Tokenize the dataset

In [10]:
#Stemming Algorithms - PorterStemmer
import nltk

In [11]:
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()
def stemmer_tokenize (text):
 return[porter.stem(word) for word in text.split()]


In [12]:
stemmer_tokenize ('coders like coding and thus they code')


['coder', 'like', 'code', 'and', 'thu', 'they', 'code']

In [13]:
#Remaining Steps:
 
#Vectorize the dataset (stem)
#Train the classifier
#Pickling the classifier
#Accuracy of the classifier

# 3) Vectorizing the dataset

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(strip_accents = None, lowercase = False,
                        tokenizer = stemmer_tokenize, use_idf = True,
                        norm ='l2', smooth_idf = True)

Y = df.sentiment.values
X = tfidf.fit_transform(df.review)

# 4) Building the Classifier

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,
                                                    random_state = 1, 
                                                    test_size = 0.5, 
                                                    shuffle = False)

In [18]:
from sklearn.linear_model import LogisticRegressionCV

clf = LogisticRegressionCV(cv = 5, scoring = 'accuracy',
                           n_jobs = 3, verbose = 3,
                           max_iter = 100).fit(X_train, Y_train)

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   2 out of   5 | elapsed:  6.0min remaining:  9.0min
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  9.7min finished


# 5) Saving The Classifier 

In [21]:
#Saving the model
saved_model = open('saved_model.sav','wb')

#using the Pickle Library function - dump - to store the classifier
import pickle
pickle.dump(clf, saved_model)

saved_model.close()

filename = 'saved_model.sav'
saved_clf = pickle.load(open(filename,'rb'))

# 6) Evaluation of The Classifier

In [22]:
saved_clf.score(X_test, Y_test)

0.88972